In [1]: exit
(base) usaxs@usaxscontrol .../USAXS_data/2025-05 $ start-bits-usaxs 
CONDA_PREFIX = '/home/beams/USAXS/.conda/envs/bits_usaxs'
Python 3.11.12 | packaged by conda-forge | (main, Apr 10 2025, 22:23:25) [GCC 13.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 9.1.0 -- An enhanced Interactive Python. Type '?' for help.
Tip: `?` alone on a line will brings up IPython's help
I Fri-16:26:30.212: **************************************** Bluesky Startup

Below are the IPython logging settings for your session.
These settings have no impact on your experiment.

Activating auto-logging. Current session state plus future input saved.
Filename       : /share1/USAXS_data/2025-05/.logs/ipython_log.py
Mode           : rotate
Output logging : True
Raw input log  : False
Timestamping   : True
State          : active
Exception reporting mode: Plain

End of IPython settings

I Fri-16:26:36.375: Starting Instrument with iconfig: /home/beams11/USAXS/bits_usaxs/src/usaxs/configs/iconfig.yml
W Fri-16:26:36.402: APS DM setup file does not exist: '/home/dm/etc/dm.setup.sh'
I Fri-16:26:36.402: Registered Bluesky IPython magics
I Fri-16:26:36.555: Databroker catalog name: usaxs
I Fri-16:26:36.556: using ophyd control layer: 'pyepics'
I Fri-16:26:36.556: RunEngine metadata saved to: .re_md_dict.yml
I Fri-16:26:37.096: SPEC data file: /share1/USAXS_data/2025-05/20250523-162637.dat
I Fri-16:26:37.097: Loading device file: /home/beams11/USAXS/bits_usaxs/src/usaxs/configs/scalers_and_amplifiers.yml
^CA 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
^Ctrying a second time
Pausing...
Traceback (most recent call last):
  Cell In[1], line 1
    from usaxs.startup import *
  File /home/beams11/USAXS/bits_usaxs/src/usaxs/startup.py:84
    RE(make_devices(file="scalers_and_amplifiers.yml", clear=False))
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/run_engine.py:976 in __call__
    raise RunEngineInterrupted(self.pause_msg) from None
RunEngineInterrupted: 
Your RunEngine is entering a paused state. These are your options for changing
the state of the RunEngine:

RE.resume()    Resume the plan.
RE.abort()     Perform cleanup, then kill plan. Mark exit_stats='aborted'.
RE.stop()      Perform cleanup, then kill plan. Mark exit_status='success'.
RE.halt()      Emergency Stop: Do not perform cleanup --- just stop.



Exception in thread Thread-2 (internal):
Traceback (most recent call last):
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/apstools/plans/run_blocking_function_plan.py", line 67, in internal
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/apsbits/core/instrument_init.py", line 132, in namespace_loader
    instrument.load(yaml_device_file)
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/guarneri/instrument.py", line 399, in load
    devices = self.make_devices(device_defns, fake=fake)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/guarneri/instrument.py", line 190, in make_devices
    device = self.make_device(
             ^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/guarneri/instrument.py", line 274, in make_device
    result = Klass(**kwargs)
             ^^^^^^^^^^^^^^^
  File "/home/beams11/USAXS/bits_usaxs/src/usaxs/devices/amplifiers.py", line 336, in __init__
    self.scaler = oregistry[scaler]
                  ~~~~~~~~~^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/ophydregistry/registry.py", line 172, in __getitem__
    return self.find(key)
           ^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/ophydregistry/registry.py", line 346, in find
    devices = self.findall(
              ^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/ophydregistry/registry.py", line 504, in findall
    raise ComponentNotFound(
ophydregistry.exceptions.ComponentNotFound: 'Could not find components matching: label="scaler0", name="scaler0"'
In [1]: exit
(base) usaxs@usaxscontrol .../USAXS_data/2025-05 $ start-bits-usaxs 
CONDA_PREFIX = '/home/beams/USAXS/.conda/envs/bits_usaxs'
Python 3.11.12 | packaged by conda-forge | (main, Apr 10 2025, 22:23:25) [GCC 13.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 9.1.0 -- An enhanced Interactive Python. Type '?' for help.
Tip: Use `%timeit` or `%%timeit`, and the  `-r`, `-n`, and `-o` options to easily profile your code.
I Sat-08:08:56.221: **************************************** Bluesky Startup

Below are the IPython logging settings for your session.
These settings have no impact on your experiment.

Activating auto-logging. Current session state plus future input saved.
Filename       : /share1/USAXS_data/2025-05/.logs/ipython_log.py
Mode           : rotate
Output logging : True
Raw input log  : False
Timestamping   : True
State          : active
Exception reporting mode: Plain

End of IPython settings

I Sat-08:09:02.703: Starting Instrument with iconfig: /home/beams11/USAXS/bits_usaxs/src/usaxs/configs/iconfig.yml
W Sat-08:09:02.721: APS DM setup file does not exist: '/home/dm/etc/dm.setup.sh'
I Sat-08:09:02.721: Registered Bluesky IPython magics
I Sat-08:09:02.815: Databroker catalog name: usaxs
I Sat-08:09:02.815: using ophyd control layer: 'pyepics'
I Sat-08:09:02.816: RunEngine metadata saved to: .re_md_dict.yml
I Sat-08:09:03.320: SPEC data file: /share1/USAXS_data/2025-05/20250524-080903.dat
I Sat-08:09:03.322: Loading device file: /home/beams11/USAXS/bits_usaxs/src/usaxs/configs/scalers_and_amplifiers.yml
^CA 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
^Ctrying a second time
Pausing...
Traceback (most recent call last):
  Cell In[1], line 1
    from usaxs.startup import *
  File /home/beams11/USAXS/bits_usaxs/src/usaxs/startup.py:84
    RE(make_devices(file="scalers_and_amplifiers.yml", clear=False))
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/run_engine.py:976 in __call__
    raise RunEngineInterrupted(self.pause_msg) from None
RunEngineInterrupted: 
Your RunEngine is entering a paused state. These are your options for changing
the state of the RunEngine:

RE.resume()    Resume the plan.
RE.abort()     Perform cleanup, then kill plan. Mark exit_stats='aborted'.
RE.stop()      Perform cleanup, then kill plan. Mark exit_status='success'.
RE.halt()      Emergency Stop: Do not perform cleanup --- just stop.



Exception in thread Thread-2 (internal):
Traceback (most recent call last):
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/apstools/plans/run_blocking_function_plan.py", line 67, in internal
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/apsbits/core/instrument_init.py", line 132, in namespace_loader
    instrument.load(yaml_device_file)
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/guarneri/instrument.py", line 399, in load
    devices = self.make_devices(device_defns, fake=fake)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/guarneri/instrument.py", line 190, in make_devices
    device = self.make_device(
             ^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/guarneri/instrument.py", line 274, in make_device
    result = Klass(**kwargs)
             ^^^^^^^^^^^^^^^
  File "/home/beams11/USAXS/bits_usaxs/src/usaxs/devices/amplifiers.py", line 335, in __init__
    self.scaler = oregistry[scaler]
                  ~~~~~~~~~^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/ophydregistry/registry.py", line 172, in __getitem__
    return self.find(key)
           ^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/ophydregistry/registry.py", line 346, in find
    devices = self.findall(
              ^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/ophydregistry/registry.py", line 504, in findall
    raise ComponentNotFound(
ophydregistry.exceptions.ComponentNotFound: 'Could not find components matching: label="scaler0", name="scaler0"'
In [1]: 
